[package]
name = "comparer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.52", features = ["derive"] }
parser = { path = "../parser" }
serde = { version = "1.0.228", features = ["derive"] }