[workspace]
members = ["comparer", "parser", "converter"]
resolver = "3"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
byteorder = "1"
csv = "1"